import Head from "next/head";
import { Inter } from "@next/font/google";
import { useEffect, useRef, useState } from "react";
import { css } from "@emotion/react";
import Button from "@components/Button";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session } = useSession();

  const [products, setProducts] = useState<
    {
      id: string;
      name: string;
      createdAt: string;
    }[]
  >([]);
  // useEffect(() => {
  //   fetch(`/api/get-items`)
  //     .then((res) => res.json())
  //     .then((data) => setProducts(data.items));
  // }, []);
  useEffect(() => {
    fetch(`/api/get-products`)
      .then((res) => res.json())
      .then((data) => setProducts(data.items));
  }, []);

  const inputRef = useRef<HTMLInputElement>(null);
  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value === "") {
      alert("name을 넣어주세요.");
      return;
    }
    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message));
  };

  return (
    <>
      <Head>
        <title>Rarla Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Rarla Commerce</h1>
        {session && <h2>안녕하세요 {session.user?.name}님</h2>}
        <div>
          <h2>Add items</h2>
          <input
            ref={inputRef}
            type="text"
            className="placeholder:italic placeholder:text-slate-400 block bg-white w-full border border-slate-300 rounded-md py-2 pl-3 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm"
            placeholder="name"
          />
          <button onClick={handleClick}>Add test</button>
        </div>

        <div>
          <h2>Products</h2>
          {products &&
            products.map((item) => (
              <div key={item.id}>
                {item.name} {item.createdAt}
              </div>
            ))}
          {/* {products &&
            products.map((item) => (
              <div key={item.id}>
                {JSON.stringify(item)}
                {item.properties &&
                  Object.entries(item.properties).map(([key, value]) => (
                    <button
                      key={key}
                      onClick={() => {
                        fetch(
                          `/api/get-detail?pageId=${item.id}&propertyId=${value.id}`
                        )
                          .then((res) => res.json())
                          .then((data) => alert(JSON.stringify(data.detail)));
                      }}
                    >
                      {key}
                    </button>
                  ))}
                <br />
                <br />
              </div>
            ))} */}
        </div>

        <Button>emotion btn</Button>
      </main>
    </>
  );
}
